### ISSUE TITLE
Use automatic labelling in our issues

### ISSUE THREAD

**Issue by MVrachev** [vmware/precaution#105]
**Is your feature request related to a problem? Please describe.**

I just thought that we can use automatic labelling on issues because we have different templates for bugs and enchantments and it will be easy for a bot or GitHub app to recognize when an issue is a bug or enchantment. 

**Describe the solution you'd like**
Install a bot or GitHub app which will do that work.

**Comment by joshuagl** [comment]
Issue #192 duplicates this issue, as that issue has more information (suggests a solution) I'll close this one.
