### ISSUE TITLE
No commit found message

### ISSUE THREAD

**Issue by ericwb** [vmware/precaution#111]
**Describe the bug**
Precaution erroring on PR of wavefront-adapter-for-istio

**To Reproduce**
1. do a dummy PR on wavefront-adapter-for-istio
2. Precaution check errors stating it couldn't find a commit
3. Then when commit is force-pushed, Precaution disappears from the listed checks
4. Reopening the PR, then Precaution reappears.

**Expected behavior**
Shouldn't see a No commit error when there is a commit.  Precaution shouldn't disappear from the listed checks.

**Screenshots**
https://github.com/vmware/wavefront-adapter-for-istio/pull/67/checks?check_run_id=51530610

**Additional context**
n/a

**Comment by MVrachev** [comment]
It is confirmed that the problem is when you create a pull request across forks.
