### ISSUE TITLE
Precaution app shows incorrect logo

### ISSUE THREAD

**Issue by venilnoronha** [vmware/precaution#133]
**Describe the bug**
@ericwb's profile picture appears in place of Precaution's logo.

**To Reproduce**
1. Create a PR on a repository that has Precaution installed.
2. Wait for GitHub to initiate checks.
3. Look at the logo beside the Precaution app.

**Expected behavior**
Precaution's logo should appear instead of Eric's profile picture.

**Screenshots**
<img width="1369" alt="screen shot 2019-02-05 at 9 22 27 pm" src="https://user-images.githubusercontent.com/1722758/52322111-a3191100-298c-11e9-94c7-7c7b2a633305.png">

**Comment by MVrachev** [comment]
Yes, we know about this problem. 
We are waiting for a logo for Precaution.

**Comment by ericwb** [comment]
So I set a temporary placeholder icon until we get an official one so it no longer shows my profile pic.

**Comment by MVrachev** [comment]
Closed by: https://github.com/vmware/precaution/pull/220
