### ISSUE TITLE
'404 Not Found' on additional documentation pages

### ISSUE THREAD

**Issue by acatinahat** [vmware/precaution#141]
**Describe the bug**
The pages listed under the "Additional documentation" section all return 404s.

**To Reproduce**
Click each link below and note that Github Pages returns a 404 response.

- [Initial setup](https://vmware.github.io/precaution/docs/initial_setup.html)
- [False positives and how to handle them](https://vmware.github.io/precaution/docs/false_positivies.html)
- [Setting up a manual deployment](https://vmware.github.io/precaution/docs/manual_deployment.html)
- [Debugging with VSCode](https://vmware.github.io/precaution/docs/local_development.html)
- [Architecture](https://vmware.github.io/precaution/docs/architecture.html)

**Expected behavior**
Documentation pages are returned.

**Comment by MVrachev** [comment]
Thank you for letting us know about this bug.

We know about it and we will work on the fix as soon as we can.
