### ISSUE TITLE
Precaution doesn't catch when there are problems parsing the AST

### ISSUE THREAD

**Issue by MVrachev** [vmware/precaution#144]
**Describe the bug**
When you run Precaution against files with syntax or other problems Precaution doesn't catch when there are problems parsing the AST.

The result from that is a "No issues found" report by Precaution on files with syntax or possibly other security issues. That way you can bypass the Precaution scan.

**To Reproduce**
1. Create a pull request with a file with syntax problem
2. Go to checks
3. The result from Precaution will be "No issues found".

**Expected behavior**
Normally I would expect the "App error" conclusion from the Precaution scan and in detail information like "syntax error while parsing AST from file".

**Comment by MVrachev** [comment]
I noticed this is a problem for both Go and Python code.
When scanning python code Bandit gives you that information about the problems when parsing the AST but in Gosec when you use the JSON output there is no information about this problem.

I start and generate results from gosec with this command: 
```gosec -fmt=json --out=result.json testData/app```
on this file which clearly misses the curly bracket of the main function (line 11):

![image](https://user-images.githubusercontent.com/16246778/52959442-df8e3900-339e-11e9-97d8-71c9521a2feb.png)
 
and the results.json content is: 
![image](https://user-images.githubusercontent.com/16246778/52959461-e87f0a80-339e-11e9-8900-60351ee8969f.png)

If you do the same command but without generating an output on the command line you will see the problem:

![image](https://user-images.githubusercontent.com/16246778/52959558-211ee400-339f-11e9-9dc7-2af9b8062205.png)

So the report we get from Gosec can be really missleading.
For Bandit we will fix it easily.

**Comment by ericwb** [comment]
Duplicate of #142
