### ISSUE TITLE
User authorization callback URL not correct

### ISSUE THREAD

**Issue by MVrachev** [vmware/precaution#159]
**Describe the bug**
When you install Precaution the idea is to be redirected to the [Inital setup page](https://vmware.github.io/precaution/initial_setup.html) but it gives 404: 
![image](https://user-images.githubusercontent.com/16246778/54271126-9722ff00-4589-11e9-96ad-be0c88fbada3.png)

**To Reproduce**
1. Install Precaution
2. It will redirect you to a incorrect webpage.

**Expected behavior**
After installation to be redirected to this [link]((https://vmware.github.io/precaution/initial_setup.html).

**Solution**
The user authorizastion callback url should be change from the Precaution app settings:
![image](https://user-images.githubusercontent.com/16246778/54271383-1284b080-458a-11e9-96fe-1843d0bd9628.png)

**Comment by ericwb** [comment]
I fixed the link in the GitHub app settings.
