### ISSUE TITLE
Bug when updating an existing across forks pull request

### ISSUE THREAD

**Issue by MVrachev** [vmware/precaution#169]
**Describe the bug**

There is one project to which you are contributing let us call it O for the original repository. 
You have your own fork of that project on GitHub let us call it F for the forked repository.

You have installed Precaution on repository F but Precaution is NOT installed on repository O.

You have already created a pull request from repo F to repo O.
You add a new commit to the existing pull request and then the following bug is shown in the logs:
![image](https://user-images.githubusercontent.com/16246778/56351632-3e710280-61d6-11e9-945d-627608e99e24.png)

**To Reproduce**
1. Create a situation and configuration for the O repository and the F repository as described above.
2. Make changes and create a pull request from your fork repo to the original repo.
3. Add a new commit to the existing pull request.
4. You can see the issue only if you have access to the logs.

**Expected behavior**
The problem here is that a pull request is created at all.
Precaution is not installed or repo O which means there is no sense to scan its pull requests.
Ignore that pull request because the original repo hasn't installed Precaution.

**Screenshots**

Example: 
This is my pull request from the : 
![image](https://user-images.githubusercontent.com/16246778/55486717-79e7ca80-5635-11e9-9ff6-7f789c62eb62.png)

I have enabled Precaution on my fork but Precaution is not yet installed on the original repo.

Here is the bug from the logs: 
![image](https://user-images.githubusercontent.com/16246778/55486652-5ae93880-5635-11e9-88e6-77c1d878e6d3.png)

**Comment by joshuagl** [comment]
_Some notes captured during an offline discussion with Martin._

We have a forked repository with Precaution installed and are opening a Pull Request from the fork to the upstream. The upstream repository does not have Precaution installed.

We are observing the `CheckSuiteEvent` webhook on the fork repository is triggered when we open (? not verified) and update (verified) Pull Requests against the upstream.

This is inline with the CheckSuiteEvent documentation, which states that:
> The `requested` action triggers when new code is pushed to the app's repository

The application installed on the fork sees the CheckSuiteEvent with the `requested` action when the branch in the fork associated with the Pull Request is updated.

We also observed that we seem to be receiving multiple CheckSuiteEvent events, though at least one of those had an empty `pull_requests` array.

**Comment by joshuagl** [comment]
We don't want the application running on the fork to run when PRs are being processed in the upstream. 

Do we need to subscribe to the `requested` action? We should, I think, run checks when the repository is updated thanks to out handling of `PullRequestEvent`'s `synchronize` action.

**Comment by MVrachev** [comment]
I was able to reproduce this bug with a test account which forked my personal repository and did the above steps.

Curiously there is no bug on the initial creation of the pr, but Precatuion still catches a webhook. I only get this: 
![image](https://user-images.githubusercontent.com/16246778/56353003-19ca5a00-61d9-11e9-8fa3-b8d1ff3d0b8f.png)

and this: 
![image](https://user-images.githubusercontent.com/16246778/56353016-1f27a480-61d9-11e9-87fa-ae7381fa8302.png)

**Comment by joshuagl** [comment]
Is the 
```javascript
if (pullRequests.length > 0) {
``` 
branch from [index.js:24](https://github.com/vmware/precaution/blob/master/index.js#L24) being triggered even though length is 0 and the array is empty? Would fixing that resolve this issue?
Is this some kind of type mismatch? Are we comparing a non-int value to an int?

The GitHub docs for [CheckSuiteEvent](https://developer.github.com/v3/activity/events/types/#checksuiteevent) say:

> __Note__: The Checks API only looks for pushes in the repository where the check suite or check run were created. Pushes to a branch in a forked repository are not detected and return an empty `pull_requests` array and a `null` value for `head_branch`.

We could update our check at index.js:24 to ensure `head_branch` is `null` and the `pull_requests` array is empty

**Comment by joshuagl** [comment]
I think we can ignore `CheckSuiteEvent` when the action is `requested`. As I understand it Precaution needs to be able to run the linters when:
1) a pull request is opened: this is captured by a `PullRequestEvent` with the `opened` (and `reopened`) action
2) a pull request is updated: this is captured by a `PullRequestEvent` with the `synchronize` action
3) the user presses the Re-run [all] checks button in the checks UI: this is captured by a `CheckSuiteEvent` with the `rerequested` action.

I don't see a need for `CheckSuiteEvent` with the `requested` action? Am I missing something?

**Comment by MVrachev** [comment]
> Is the
> 
> ```js
> if (pullRequests.length > 0) {
> ```
> 
> branch from [index.js:24](https://github.com/vmware/precaution/blob/master/index.js#L24) being triggered even though length is 0 and the array is empty? Would fixing that resolve this issue?
> Is this some kind of type mismatch? Are we comparing a non-int value to an int?
> 
> The GitHub docs for [CheckSuiteEvent](https://developer.github.com/v3/activity/events/types/#checksuiteevent) say:
> 
> > **Note**: The Checks API only looks for pushes in the repository where the check suite or check run were created. Pushes to a branch in a forked repository are not detected and return an empty `pull_requests` array and a `null` value for `head_branch`.
> 
> We could update our check at index.js:24 to ensure `head_branch` is `null` and the `pull_requests` array is empty

I made a mistake with the prints:
![image](https://user-images.githubusercontent.com/16246778/56356716-4fc00c00-61e2-11e9-9343-d46e9289945c.png)

So, don't look at this.

**Comment by joshuagl** [comment]
Hmm, why didn't the fixes tag in #199 close this automatically?
