### ISSUE TITLE
Documentation changes merged by mergify don't get automatically deployed

### ISSUE THREAD

**Issue by joshuagl** [vmware/precaution#205]
**Describe the bug**
When mergify merges a commit which changes the docs the updated docs aren't automatically rebuilt and pushed to our GitHub pages

**Additional context**
If I manually merge the commit, rather than having mergify do it, the Pages are built and deployed successfully. See PR #186 for an example, merging of which added a new page to the docs at https://vmware.github.io/precaution/local_docs_build.html

**Comment by joshuagl** [comment]
Looks like we aren't the only people running into this issue with Mergify: https://stackoverflow.com/questions/55756906/page-build-failed-after-auto-merging-pull-request-to-github-pages-master-branc

**Comment by joshuagl** [comment]
Reading over GitHub's docs for [User, Organization, and Project Pages](https://help.github.com/en/articles/user-organization-and-project-pages) I infer that automatic doc builds should work when the committer is a member of the project with a verified email address (this isn't explicitly stated, but reflects what is stated for User and Organization Pages) - I wonder if the mergify bot has a verified email address?

**Comment by MVrachev** [comment]
> Reading over GitHub's docs for [User, Organization, and Project Pages](https://help.github.com/en/articles/user-organization-and-project-pages) I infer that automatic doc builds should work when the committer is a member of the project with a verified email address (this isn't explicitly stated, but reflects what is stated for User and Organization Pages) - I wonder if the mergify bot has a verified email address?

Good progress and a good question.
Have you created an issue in the mergify GitHub webapge?

**Comment by MVrachev** [comment]
Curiously GitHub pages were updated now. Hmmm... did you do something?

**Comment by joshuagl** [comment]
The GitHub Pages were updated when I manually merged PR #186.

Thanks for the prompt, I've filed Mergifyio/mergify-engine#386 to track the issue with the upstream.

**Comment by joshuagl** [comment]
I've also reached out to GitHub support to see if they can help diagnose the issue.

**Comment by MVrachev** [comment]
There is one small bug, not sure if it's Mergify fault or ours but in this pull request - [Remove redundant second package manager - yarn](https://github.com/vmware/precaution/pull/208) I fix this issue:[Using npm and yarn at the same time]https://github.com/vmware/precaution/issues/190 and issue 190 didn't automatically close.

**Comment by joshuagl** [comment]
GitHub support have informed me that there's a protection mechanism in place that prevents bot users from automatically building GitHub Pages. Upstream are considering what to do with this.
