### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by joshuagl** [vmware/precaution#219]
**Is your feature request related to a problem? Please describe.**
Releases of the App should be automated such that we have a robust and worry-free mechanism to deploy new versions of Precaution to production.

**Describe the solution you'd like**
Releasing the App should require as little human intervention as possible, ideally it would be as simple as tagging the GitHub repository with a release but may also involve running a deployment script.

**Additional context**
An automated and robust release process makes deploying new versions of the application less error-prone and removes burden on making releases, enabling a release early release often mindset to be employed for Precaution.

**Comment by ericwb** [comment]
Is this a dup of https://github.com/vmware/precaution/issues/84 or something different?

**Comment by joshuagl** [comment]
Looks like a duplicate of #84, but I didn't see it as that issue is closed.

**Comment by ericwb** [comment]
Yeah, #84 is closed because we implemented it.  So Travis-CI has a deployment step that will deploy to Heroku whenever a git tag and release is made.

**Comment by joshuagl** [comment]
Oh, great. Closing this issue.
