### ISSUE TITLE
TypeScript filter potentially will match files without ".ts" ending

### ISSUE THREAD

**Issue by ericwb** [vmware/precaution#224]
**Describe the bug**
See
https://github.com/vmware/precaution/blob/master/linters/tslint.js#L29

The filter is looking for "ts" instead of ".ts".  Thus that could match with "tests" or any file name ending with "ts"

**To Reproduce**
Code inspection

**Expected behavior**
Expect the filter to be ".ts"

**Screenshots**
n/a

**Additional context**
n/a

**Comment by MVrachev** [comment]
Fixed by: https://github.com/vmware/precaution/pull/225
