### ISSUE TITLE
Create a documentation page

### ISSUE THREAD

**Issue by ericwb** [vmware/precaution#66]
**Is your feature request related to a problem? Please describe.**
Precaution could use a project documentation page.  Ideally using something like GitHub pages.

**Describe the solution you'd like**
So if we create a /docs folder on the master branch to house our documentation, then we can publish to:
https://vmware.github.io/precaution

Instructions can be found here:
https://help.github.com/articles/user-organization-and-project-pages/

**Describe alternatives you've considered**
Some other doc hosting can also be used, but GitHub pages seems the most ideal.

**Additional context**
n/a

**Comment by ericwb** [comment]
Ok, https://vmware.github.io/precaution/ is now created.  But it's currently using just the README.  Would be better to have proper documentation setup in a docs/ directory.

**Comment by MVrachev** [comment]
I am not sure what do we want to write on this documentation page.
Our app is really straightforward.

**Comment by MVrachev** [comment]
I think we can close that. We already have a documentation page.
