### ISSUE TITLE
Missing copyright in some files

### ISSUE THREAD

**Issue by ericwb** [vmware/precaution#68]
**Describe the bug**
I found the following files are missing copyrights:
.github/ISSUE_TEMPLATE/--bug-report.md
.github/ISSUE_TEMPLATE/--feature-report.md
.gitignore
.profile
_config.yml
CONTRIBUTING.md
README.md
requirements.txt
yarn.lock

**Comment by evqna** [comment]
I am not sure it is possible to write comments in some of these files (yarn.lock is autogenerated, markdown doesn't support comments).
Is it necessary to have a copyright statement in all of these? Most projects I am looking at don't seem to be doing it.

**Comment by ericwb** [comment]
So we should add copyrights to whatever files it is possible.  JSON files are problematic, but believe you can use  in markdown

**Comment by evqna** [comment]
This doesn't work for GitHub issue/PR templates as the contents of the comment are copied into the text editor.
