### ISSUE TITLE
Respect the linter configs files

### ISSUE THREAD

**Issue by MVrachev** [vmware/precaution#81]
We use different linters for Precaution and I think we should respect the configuration files the people are using for those linters.

Also I think that this will give the users an opportunity to set up a specific for a linter options when using Precaution.

**Describe the solution you'd like**
If there is a config file for a specific linter - respect it and use it instead of the default settings.

**Comment by ericwb** [comment]
I'm not sure we should do this as it will become confusing to users if they use both bandit config and precaution config.

**Comment by MVrachev** [comment]
Yep, maybe the best way to do it will be with single .precaution.ymal file in which the users can give Bandit, Gosec specific options and which linters they want to use for Precaution etc.
