### ISSUE TITLE
Automated deployment to Heroku

### ISSUE THREAD

**Issue by ericwb** [vmware/precaution#84]
**Is your feature request related to a problem? Please describe.**
We could use a function that automatically published the code to Heroku.

**Describe the solution you'd like**
So with each PR merged we should publish to the dev version of Heroku precaution probot site.  And with each release we tag in Git, it should publish to the production Heroku site.

**Describe alternatives you've considered**
We might be able to make use of GitHub actions.

**Additional context**
https://docs.travis-ci.com/user/deployment/heroku/

**Comment by MVrachev** [comment]
If we want to publish to the dev version dev version of Heroku precaution probot site we would need a third dyno.
Right now I use dev-precaution dyno (or Heroku app) for testing purposes.

**Comment by MVrachev** [comment]
I will create a third dyno for testing. We can use the dev-precaution heroku app (dyno) to store there our app with it's latest successful master build.
