### ISSUE TITLE
After Install of Precaution we should redirect admins how to set branch protection rule

### ISSUE THREAD

**Issue by ericwb** [vmware/precaution#93]
**Describe the bug**
Currently Precaution doesn't block a PR from merging even when high severity, high confidence issues are found.

**To Reproduce**
1. install Precaution on a repo
2. notice in the admin settings of the repo there is no rule to prevent merging of PRs that don't pass Precaution status checks

**Expected behavior**
We should create a "additional setup URL" document for admins after installing the app. 

We can also refer to: https://help.github.com/articles/configuring-protected-branches/

**Screenshots**
n/a

**Additional context**
n/a

**Comment by MVrachev** [comment]
I found a project which should use that. The project is called WIP: https://github.com/wip/app
The idea of the project is to stop a pull request from merging if it has WIP/Work in progress in the title.

I created an issue with the question how do they achieve that and I am waiting for an answer.
