### ISSUE TITLE
Create "How it works" diagram

### ISSUE THREAD

**Issue by MVrachev** [vmware/precaution#97]
**Is your feature request related to a problem? Please describe.**

I think it would be useful if we use "How it works" diagram as shown here:
https://github.com/wip/app/blob/master/HOW_IT_WORKS.md
That way it would be a lot easier for future developers to start contributing to our project.

**Describe the solution you'd like**
We can use block diagrams for that purpose or something else.

**Comment by evqna** [comment]
I can do this if you are not already working on it.

**Comment by MVrachev** [comment]
I am not working on this right now. You can do it if you want. :))
